name: nolycompta
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.2.0
  step_progress_indicator: ^1.0.2
  email_validator: ^2.1.17
  flutter_verification_code: ^1.1.6
  flutter_native_splash: ^2.2.10+1
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_native_splash:
  color: "#FFFFFF"
  image: assets\images\logos\noly_only.png

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/shapes/
    - assets/images/icons/
    - assets/images/logos/

  fonts:
    - family: DemiBold
      fonts:
      - asset: assets/fonts/DemiBold.ttf

    - family: Medium
      fonts:
      - asset: assets/fonts/Medium.ttf

    - family: Regular
      fonts:
      - asset: assets/fonts/Regular.ttf
